[package]
name = "tertestrial"
version = "0.0.2"
authors = ["Kevin Goslar <kevin.goslar@gmail.com>"]
edition = "2021"

[dependencies]
ctrlc = { version = "3.4", features = ["termination"] }
glob = "0.3.1"
nix = "0.19.1"
prettytable-rs = "^0.8"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
shellwords = "1.1.0"
termcolor = "1.4"
terminal_size = "0.1"
clap = "2.34.0"

[profile.dev]
panic = "unwind"

[profile.release]
opt-level = 's'    # Optimize for size
lto = true         # enable link-time optimization (removes dead code)
codegen-units = 1  # reduce codegen units to enable additional optimizations
panic = "unwind"
