name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "contest"
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: make setup
      - run: make test
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
